import './globals.css'

import { Inter } from 'next/font/google'

import { Layout } from '@/components/layout/Layout'
import { MainFooter } from '@/components/layout/MainFooter'
import { MainNav } from '@/components/layout/MainNav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: {
    template: '%s | SuperEffective Assets Manager',
    default: 'SuperEffective Assets Manager',
    absolute: 'SuperEffective Assets Manager',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          <MainNav />
          <main className="flex flex-col items-center justify-between lg:px-24 w-full">
            {children}
          </main>
          <MainFooter />
        </Layout>
      </body>
    </html>
  )
}
