export enum Routes {
  Home = '/',
  Pokemon = '/data/pokemon',
  Abilities = '/data/abilities',
  Items = '/data/items',
  Ribbons = '/data/ribbons',
  Marks = '/data/marks',
  Pokedexes = '/data/pokedexes',
  Sprites = '/data/sprites',
  Families = '/data/families',
  Moves = '/data/moves',
  Games = '/data/games',
  Locations = '/data/locations',
  LegacyBoxPresets = '/data/box-presets',
}
