name: 'Check code quality'
description: 'Checks code quality: prettier, linters, build and test'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: pnpm prettier-check

    - shell: bash
      run: pnpm type-check

    - shell: bash
      run: pnpm lint

    - shell: bash
      run: pnpm build

    - shell: bash
      run: pnpm publint-check

    - shell: bash
      run: pnpm data:validate

    - shell: bash
      run: pnpm test:ci
