name: 'Setup project'
description: 'Sets up project and its dependencies'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: ${{ env.PNPM_VERSION }}
        run_install: false

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        # registry-url: https://npm.pkg.github.com
        cache: 'pnpm'
        cache-dependency-path: './pnpm-lock.yaml'

    - uses: actions/cache@v3
      name: Setup cache for turbo
      with:
        path: .turbo
        key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ github.job }}-${{ github.ref_name }}-

    - shell: bash
      run: pnpm install --frozen-lockfile

    - shell: bash
      name: Copy .env.dist to .env
      run: cp .env.dist .env
